import { default as PATHS } from "./paths";
import { DefaultTheme } from "vitepress";
import * as SIDEBARS from "./sidebars/index.ts";

const ALL_SIDEBARS:DefaultTheme.SidebarMulti = {
    [PATHS.HOME]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    // Frontend
    [PATHS.FRONTEND_HTML]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_CSS]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_JS]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_BOOTSTRAP]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_SASS]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_JEST]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_TS]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_VUE]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_VTU]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_ANGULAR]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_WEBPACK]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    [PATHS.FRONTEND_VITE]: SIDEBARS.SIDEBAR_DEFAULT_FRONTEND,
    // Backend
    [PATHS.BACKEND_JAVA]: SIDEBARS.SIDEBAR_JAVA,
    [PATHS.BACKEND_SPRING]: SIDEBARS.SIDEBAR_SPRING,
    [PATHS.BACKEND_HIBERNATE]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_JUNIT]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_CUCUMBER]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_OBJECT_MAPPER]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_JSON]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_XML]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_LOMBOK]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_LOGGER]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    [PATHS.BACKEND_FEIGN]: SIDEBARS.SIDEBAR_DEFAULT_BACKEND,
    // APIs
    [PATHS.API_HTTP]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_CORS]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_REST]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_WEBSERVICES]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_MICROSERVICES]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_SWAGGER]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_OPENAPI]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_KAFKA]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_RABBIT_MQ]: SIDEBARS.SIDEBAR_DEFAULT_API,
    [PATHS.API_OWASP]: SIDEBARS.SIDEBAR_DEFAULT_API,
    // Devops & CICD
    [PATHS.DEVOPS_GIT]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_GRADLE]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_JENKINS]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_CONTAINERIZATION]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_DOCKER]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_PUPPET]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_NGINX]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_KUBERNETES]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_NOMAD]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_ELK]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    [PATHS.DEVOPS_GRAFANA]: SIDEBARS.SIDEBAR_DEFAULT_DEVOPS,
    // SWE
    [PATHS.SWE_CLEAN_CODE]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    [PATHS.SWE_DESIGN_PATTERNS]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    [PATHS.SWE_CLOUD_COMPUTING]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    [PATHS.SWE_DISTRIBUTED_SYSTEMS]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    [PATHS.SWE_SYSTEM_DESIGN]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    [PATHS.SWE_SYSTEM_DESIGN_EXAMPLES]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    [PATHS.SWE_AWS]: SIDEBARS.SIDEBAR_DEFAULT_SWE,
    // CSE
    [PATHS.CSE_DS]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_ALGO]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_OS]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_DBMS]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_CN]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_PROG_BASIC]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_CHEATSHEET]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    [PATHS.CSE_PUZZLES]: SIDEBARS.SIDEBAR_DEFAULT_CSE,
    // AI
    [PATHS.AI_INTRO]: SIDEBARS.SIDEBAR_DEFAULT_AI,
    // Misc
    [PATHS.MISC_REFS]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    [PATHS.MISC_API_EXAMPLES]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    [PATHS.MISC_MARKDOWN_EXAMPLES]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    [PATHS.MISC_JEKYLL]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
    [PATHS.MISC_CHROME]: SIDEBARS.SIDEBAR_DEFAULT_MISC,
}

export default ALL_SIDEBARS;